spring.application.name=Rest API

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=ScalaREST
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web.reactive.function.server=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
